# Generated by Django 4.1.7 on 2023-02-23 12:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_textmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmodel',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
