from .contact import contact
from .home import home
from .category import categoryListView
from .mytext import mytext
from .detail import detailView
from .addText import addText
from .updateText import updateText
from .deleteText import deleteText
from .deleteComment import deleteComment